export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const SET_BOARD_STATE_AT_TURN_START = 'SET_BOARD';
export type SET_BOARD_STATE_AT_TURN_START = typeof SET_BOARD_STATE_AT_TURN_START;

export const SET_PHASE = 'SET_PHASE';
export type SET_PHASE = typeof SET_PHASE;

export const ADD_MOVED_PIECE = 'ADD_MOVED_PIECE';
export type ADD_MOVED_PIECE = typeof ADD_MOVED_PIECE;

export const RESET_PIECES_THAT_HAVE_MOVED_ON_CURRENT_TURN = 'RESET_PIECES_THAT_HAVE_MOVED_ON_CURRENT_TURN';
export type RESET_PIECES_THAT_HAVE_MOVED_ON_CURRENT_TURN = typeof RESET_PIECES_THAT_HAVE_MOVED_ON_CURRENT_TURN;